# Site settings
name: Amaan Afzal
title: Software Developer
email: amaanafzalcs@gmail.com
url: https://github.com/Amaan6868
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: "your keywords, separated by commas"
skills: "Full-Stack Developer - Versatile in Multiple Programming Languages - Database Specialist"
meta_author: Afzal Amaan

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 5D3FD3
  primary-rgb: "93,63,211" 
  secondary: 000000 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Amaan Afzal
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: LinkedIn
    url: https://www.linkedin.com/in/amaan-afzal-a72374288/
  - title: github
    url: http://github.com/Amaan6868
  


defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
